/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. */
//4613732
public class ProblemTwo {
  static int x, y, sum, alt;
  public static void main(String[] args) {
    x = 1;
    y = 2;
    sum = 0;
    alt = 0;
    while (y < 4000000 || x < 4000000) {
      adder();
    }
    System.out.println(sum/2);
  }
  public static void adder() {
    if (x < 100)
    System.out.println(x);
    if (y < 100)
    System.out.println(y);

    if (x%2==0)
    sum += x;
    if (y%2==0)
    sum += y;
    if (alt%2==0)
    x+=y;
    else
    y+=x;
    alt++;
  }
}
