/*The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */
//76576500
import java.util.ArrayList;
public class ProblemTwelve {
  public static void main(String[] args) {
    long adder = 2L;
    long triNum = 1L;
    int divBound = 250;
    ArrayList<Long> divs = new ArrayList<>();
    while (divs.size() < divBound) {
      for (long x = 1L; x <= (int)Math.sqrt(triNum)+1; x++) {
        if (triNum % x == 0) {
          divs.add(x);
        }
      }
      System.out.println(divs.size());
      if (divs.size() < divBound) {
        triNum += adder;
        adder++;
        divs.clear();
      }
    }
    System.out.format("%d%n",triNum);
  }
}